### PR TITLE
Set content type

### LINKED ISSUE #79: Send hash to JSON API
ActiveRestClient is correctly configured in the rails app. I can find a contact, but when I'm trying to `update` no body is sent. I couldn't find out why, but trying using POST for debugging.

```
# model contact
class Contact < ActiveRestClient::Base
  request_body_type :json
  verbose true

  get :find, "/contacts/:id"
  post :save, "/contacts/post/:id"
end
```

```
#controler contact
def update
    if Contact.save(id: params["id"], contact: params["contact"])
   (...)
end
```

I'm trying to send an Hash (params["contact"]) to the API:
`{"contact" => {"contact_info" => {"name" => "sdfgsdfg"}}}`

When I try to send it using the CURL via terminal the params received in the API are:
`{"contact"=>{"contact_info"=>{"name"=>"Philipp123"}}, "splat"=>[], "captures"=>["54dd076c3465300003380000"], "id"=>"54dd076c3465300003380000"}`

When I do it in the rails app I receive:
`{"{\"contact\":{\"contact_info\":{\"name\":\"sdfgsdfg\"}}}"=>nil, "splat"=>[], "captures"=>["54dd076c3465300003380000"], "id"=>"54dd076c3465300003380000"}`

What am I doing wrong? How do I send an hash?

### PR DESCRIPTION
**Pull request by tiagotex**
Set `Content-Type` for default and JSON.

### CODE REVIEW

**Comment by tiagotex** [comment]
resolve #79

**Comment by tiagotex** [comment]
I'm thinking we should also enforce the default charset for JSON should be `UTF-8`.

@andyjeffries What's your opinion to change `Content-type` for JSON from `application/json` to `application/json; charset=utf-8`

**Comment by andyjeffries** [comment]
I agree with this in principle, however my only concern is - if that's the default, how will users change it?

**Comment by tiagotex** [comment]
In `request.rb`:

```
def call(explicit_parameters=nil)
  (...)
  if object_is_class?
    @object.send(:_filter_request, :before, @method[:name], self)
  else
    @object.class.send(:_filter_request, :before, @method[:name], self)
  end

  append_get_parameters
  prepare_request_body_type
  (...)
end
```
Move `append_get_parameters` and `prepare_request_body_type` before `if object_is_class?`, this way the header is defined but can be overridden using `before_request`:

```
# In model
before_request :change_content_type


def change_content_type(name, request)
  if name == :save
      request.headers["Content-Type"] = "application/json"
    end
end
```

**Comment by andyjeffries** [comment]
Not such a fan of that - as before_request may well be used by lots of people to mess around with the request params before the body is generated.  A better solution may be to only set the Content-Type header if it's not already set?  That way people can still tweak it in a before_request.

**Comment by andyjeffries** [comment]
P.S. I take it you saw the two failing tests now? ;-)

**Comment by tiagotex** [comment]
Yes, it was my mistake.

Setting up content-type type only if not defined seems to be a perfect solution.

**Comment by andyjeffries** [comment]
Thanks for this, merged in.

**Pull request merged**
